# Copyright 2019-2020 The OpenEBS Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This Dockerfile builds node-disk-manager
#

FROM ubuntu:16.04 AS build-stage

LABEL APP="node-disk-manager"
LABEL REPO="https://github.com/EdgeCloudx/node-disk-manager"

RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    apt-get update --fix-missing && \
    apt-get install gcc make git wget libudev-dev libblkid-dev -y

RUN wget -P /tmp https://studygolang.com/dl/golang/go1.17.5.linux-amd64.tar.gz && \
     tar -C /usr/local -xzf /tmp/go1.17.5.linux-amd64.tar.gz

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

#we need openSeaChest repo to build node-disk-manager
RUN cd $GOPATH/src && \
    git clone --recursive --branch Release-19.06.02 https://github.com/openebs/openSeaChest.git && \
    cd openSeaChest/Make/gcc && \
    make release && \
    cd ../../ && \
    cp opensea-common/Make/gcc/lib/libopensea-common.a /usr/lib && \
    cp opensea-operations/Make/gcc/lib/libopensea-operations.a /usr/lib && \
    cp opensea-transport/Make/gcc/lib/libopensea-transport.a /usr/lib

ADD . $GOPATH/src/node-disk-manager
WORKDIR $GOPATH/src/node-disk-manager

RUN make bootstrap 
